ngageoint/mrgeo

mrgeo-services/mrgeo-services-wcs/src/main/java/org/mrgeo/resources/wcs/WcsGenerator.java
mrgeo-services/mrgeo-services-wcs/src/main/java/org/mrgeo/services/wcs/WcsCapabilities.java

We already had WCS 1.1.0 describeCoverage, but needed getCapabilities.  getCoverage is unchanged

Added WCS getCapabilities for version 1.1.0

---

mrgeo-cmd/mrgeo-cmd-webserver/src/main/java/org/mrgeo/cmd/server/WebServer.java

It checks for a setting in mrgeo.conf named web.server.static.root and allows content to be found from there. The value of that setting must be an accessible directory on the system where the web server is run from.

Add support to command line web server for serving static content

---

mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/binarymath/RawBinaryMathMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/unarymath/RawUnaryMathMapOp.scala

- change for loops to while loops
- change for #174

Performance improvement in RawBinaryMathMapOp

---

mrgeo-core/src/main/scala/org/mrgeo/utils/GDALUtils.scala
mrgeo-core/src/main/scala/org/mrgeo/utils/SparkUtils.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-costdistance/src/main/scala/org/mrgeo/mapalgebra/CostDistanceMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-costdistance/src/main/scala/org/mrgeo/mapalgebra/LeastCostPathCalculator.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/KernelMapOp.scala

Additional performance optimization converting numeric for loops to while loops

---

mrgeo-core/src/main/scala/org/mrgeo/utils/GDALUtils.scala

Check for null nodata value from source image during ingest

---

scripts/mvn-build

In file /mrgeo/scripts/mvn-build an extra dash was removed

---

mrgeo-core/src/main/scala/org/mrgeo/utils/GDALUtils.scala

Modification to allow ingesting imagery of type byte

---

mrgeo-python/src/main/python/pymrgeo/mrgeo.py

Allow a list of images to be passed to stats, mosaic and bandcombine in python

---

pom.xml
scripts/mvn-build

- renamed 'emr' profile to 'emr-4.5.0'
- added a profile for emr-4.4.0

Changes to support multiple versions of EMR

---

mrgeo-cmd/mrgeo-cmd-export/src/main/java/org/mrgeo/cmd/export/Export.java
mrgeo-core/src/main/java/org/mrgeo/data/image/MrsImageDataProvider.java
mrgeo-core/src/main/java/org/mrgeo/hdfs/image/HdfsMrsImageDataProvider.java
mrgeo-dataprovider/mrgeo-dataprovider-accumulo/src/main/java/org/mrgeo/data/accumulo/image/AccumuloMrsImageDataProvider.java

Fix NullPointerException in export

---

pom.xml

- fix version mismatches with some jetty artifacts
- closes #314

Fix problem with starting stand-alone web server when geowave data provider is included in the build

---

mrgeo-core/src/main/java/org/mrgeo/hdfs/input/image/HdfsMrsPyramidRecordReader.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/input/image/HdfsMrsPyramidRecordReaderTest.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/ConfigurationBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/FileSplitBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/FileSystemBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/HdfsMrsImageReaderBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/KeyValueHelper.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/MapFileReaderBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/PathBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/SequenceFileReaderBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/TaskAttemptContextBuilder.java
mrgeo-core/src/test/java/org/mrgeo/hdfs/utils/TiledInputSplitBuilder.java
pom.xml

Updated unit tests for HdfsPyramidRecordReader.

Unit Tests for HdfsMrsPyramidRecordReader

---

mrgeo-core/src/main/java/org/mrgeo/hdfs/input/image/HdfsMrsPyramidInputFormat.java
pom.xml

- closes #314
- Also fixed a problem in HDFS data provider class reported by findbugs

Re-fix dependency problems with jetty when GeoWave is included in our build

---

mrgeo-python/src/main/python/pymrgeo/java_gateway.py

Includes a timeout for the initial connection
closes #335

Implement alternate process for connecting to mrgeo from python

---

mrgeo-core/pom.xml
mrgeo-core/src/test/scala/org/mrgeo/mapalgebra/utils/RasterMapOpBuilder.scala
mrgeo-core/src/test/scala/org/mrgeo/mapalgebra/utils/RasterMapOpTestSupport.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/test/scala/org/mrgeo/mapalgebra/CropMapOpTest.scala

This test does not include testing when the input map op is MrsPyramidMapOp.  Will need to do some further research to figure out how to test that scenario.

Added framework to support RasterMapOp unit testing and implemented unit test for CropMapOp

---

pom.xml
scripts/mvn-build

- closes # 376
- also renamed EMR profiles for consistency with existing CDH profiles

Update final classifiers for EMR builds

---

mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/kernel/GaussianLaplacianGeographicKernel.scala

- Replace the use of an opencv matrix to keep track of the nodata mask with a
scala
array
- Use instance variables for the opencv data Matrix and nodata mask to limit
the
amount of memeory allocation and deallocation

Modify the computations for gaussian and laplacian kernels for better memory management

---

mrgeo-cmd/mrgeo-cmd-webserver/pom.xml
mrgeo-core/pom.xml
mrgeo-core/src/main/java/org/mrgeo/core/MrGeoProperties.java
mrgeo-core/src/main/scala/org/mrgeo/ingest/IngestImage.scala
mrgeo-core/src/main/scala/org/mrgeo/utils/GDALUtils.scala
mrgeo-services/pom.xml
pom.xml

Create tmp GDAL file on ingest, instead of in-memory

---

mrgeo-core/src/main/java/org/mrgeo/geometry/Reprojector.java
mrgeo-services/mrgeo-services-core/src/main/java/org/mrgeo/services/mrspyramid/rendering/ImageRendererAbstract.java
mrgeo-services/mrgeo-services-core/src/main/java/org/mrgeo/services/utils/RequestUtils.java
mrgeo-services/mrgeo-services-wms/testFiles/org.mrgeo.resources.wms/BadRequestTest/wms-invalid-coordsys.xml
mrgeo-services/mrgeo-services-wms/testFiles/org.mrgeo.resources.wms/GetMapTest/testGetMapInvalidLayer.xml

- Was hard-coded to expect an "EPSG:" string
- Fixes #444

Fix bug in handling SRS passed to WMS

---

mrgeo-services/mrgeo-services-wms/src/test/java/org/mrgeo/resources/wms/WmsGeneratorTestAbstract.java
mrgeo-services/mrgeo-services-wms/testFiles/org.mrgeo.resources.wms/BadRequestTest/wms-invalid-coordsys.xml
mrgeo-services/mrgeo-services-wms/testFiles/org.mrgeo.resources.wms/GetMapTest/testGetMapInvalidLayer.xml
pom.xml
scripts/mvn-build

- Also changed auto-generate test flag to false

Update POM for CDH 5.10.1

---

mrgeo-cmd/mrgeo-cmd-quantiles/src/main/java/org/mrgeo/cmd/quantiles/Quantiles.java
mrgeo-core/src/main/scala/org/mrgeo/quantiles/Quantiles.scala
mrgeo-core/src/main/scala/org/mrgeo/utils/SparkUtils.scala

Modify the quantiles command line to store quantiles in metadata

---

color-scales/elevation-quantile.xml
color-scales/green-blue.xml
color-scales/green-yellow-red.xml
color-scales/rainbow-transparent-quantile.xml
mrgeo-cmd/mrgeo-cmd-export/src/main/java/org/mrgeo/cmd/export/Export.java
mrgeo-core/src/main/java/org/mrgeo/colorscale/ColorScale.java
mrgeo-core/src/main/java/org/mrgeo/colorscale/applier/ColorScaleApplier.java
mrgeo-core/src/main/java/org/mrgeo/colorscale/applier/JpegColorScaleApplier.java
mrgeo-core/src/main/java/org/mrgeo/colorscale/applier/PngColorScaleApplier.java
mrgeo-core/src/test/java/org/mrgeo/colorscale/ColorScaleTest.java
mrgeo-services/mrgeo-services-core/src/main/java/org/mrgeo/services/mrspyramid/MrsPyramidService.java
mrgeo-services/mrgeo-services-core/src/main/java/org/mrgeo/services/mrspyramid/rendering/ImageRenderer.java
mrgeo-services/mrgeo-services-core/src/main/java/org/mrgeo/services/mrspyramid/rendering/ImageRendererAbstract.java
mrgeo-services/mrgeo-services-core/src/test/java/org/mrgeo/resources/mrspyramid/RasterResourceTest.java
mrgeo-services/mrgeo-services-tms/src/main/java/org/mrgeo/resources/tms/TileMapServiceResource.java
mrgeo-services/mrgeo-services-wms/src/main/java/org/mrgeo/resources/wms/WmsGenerator.java

Implement color scaling based on quantile values

---

mrgeo-core/src/main/scala/org/mrgeo/mapalgebra/MapAlgebra.scala
mrgeo-core/src/main/scala/org/mrgeo/mapalgebra/raster/MrsPyramidMapOp.scala
mrgeo-core/src/main/scala/org/mrgeo/mapalgebra/raster/RasterMapOp.scala
mrgeo-core/src/main/scala/org/mrgeo/mapalgebra/raster/SaveRasterMapOp.scala
mrgeo-core/src/test/scala/org/mrgeo/mapalgebra/utils/RasterMapOpBuilder.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-costdistance/src/main/scala/org/mrgeo/mapalgebra/CostDistanceMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/BandCombineMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/BandExtractMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/BuildPyramidMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/ChangeClassificationMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/ConvertMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/CropMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/ExportMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/FillMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/IngestImageMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/KernelMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/MosaicMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/NormalizeMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/QuantilesMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/RawFocalMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/StatisticsMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-image/src/main/scala/org/mrgeo/mapalgebra/ZoomMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-integrationtests/src/test/java/org/mrgeo/mapalgebra/MapAlgebraIntegrationTest.java
mrgeo-mapalgebra/mrgeo-mapalgebra-rasterizevector/src/main/scala/org/mrgeo/mapalgebra/AbstractRasterizeVectorMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/ConMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/LogMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/binarymath/RawBinaryMathMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-rastermath/src/main/scala/org/mrgeo/mapalgebra/unarymath/RawUnaryMathMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-terrain/src/main/java/org/mrgeo/mapalgebra/SlopeAspectMapOp.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-terrain/src/main/scala/org/mrgeo/mapalgebra/Slope8MapOp.scala

- closes #393
- report an error if an attempt is made to process images at different zoom levels
- add a new "zoom" map algebra function

Add a zoom map algebra function

---

mrgeo-core/src/main/java/org/mrgeo/geometry/GeometryCollectionImpl.java
mrgeo-core/src/main/java/org/mrgeo/utils/GeometryUtils.java
mrgeo-core/src/main/scala/org/mrgeo/ingest/IngestImage.scala
mrgeo-core/src/main/scala/org/mrgeo/job/KryoRegistrar.scala
mrgeo-core/src/main/scala/org/mrgeo/job/MrGeoDriver.scala
mrgeo-core/src/main/scala/org/mrgeo/job/yarn/MrGeoYarnDriver.scala
mrgeo-core/src/main/scala/org/mrgeo/job/yarn/MrGeoYarnJob.scala
mrgeo-core/src/main/scala/org/mrgeo/utils/GDALUtils.scala
mrgeo-mapalgebra/mrgeo-mapalgebra-costdistance/src/main/scala/org/mrgeo/mapalgebra/CostDistanceMapOp.scala
pom.xml
scripts/mvn-build

JTS interpreted a polygon as self-crossing because of precision errors.  Capture the exception in the intersects method

Catch JTS TopologyException (precision errors)

---

mrgeo-cmd/mrgeo-cmd-webserver/src/main/java/org/mrgeo/cmd/server/WebServer.java

HTTPS isn't well tested, only a quick, self-signed cert test

Add optional host parameter.  As well as HTTPS server support
